In [45]:
import sys
sys.path.append('../')

import numpy as np
import pandas as pd
from sklearn import model_selection
import collections
from util import DataManager

In [254]:
data = DataManager.get_train_data()

data['fold'] = -1
classes = (
    np.where(data.data_provider == 'karolinska', 6, 0)
    + data.isup_grade.values)
skf = model_selection.StratifiedShuffleSplit(
    n_splits=1,
    test_size=0.2,
    random_state=42)
skf_iterator = skf.split(
    X=data.image_id,
    y=classes)
train_idx, valid_idx = next(skf_iterator)
data.loc[valid_idx, 'fold'] = 0
data.loc[train_idx, 'fold'] = 1

similar = np.load('../input_/similar_examples_hash094.npy')
assign_fold = {0: [], 1: []}
for xid, yid in similar:
    xid_fold = data.loc[xid, 'fold']
    if xid not in assign_fold[0] and xid not in assign_fold[1]:
        assign_fold[xid_fold].append(xid)
    if yid not in assign_fold[0] and yid not in assign_fold[1]:
        assign_fold[xid_fold].append(yid)
for k, v in assign_fold.items():
    data.loc[v, 'fold'] = k


In [260]:
data.loc[756]

image_id         134b29504e8774c3d38102d6ee81cdb9
data_provider                             radboud
isup_grade                                      4
gleason_score                                 4+4
fold                                            0
Name: 756, dtype: object

In [113]:
groups

array([[   12,  7809],
       [   22,  5629],
       [   28,  4819],
       [   29,  5537],
       [   30,  5014],
       [   31,  6284],
       [   31,  7904],
       [   34,  8473],
       [   64,  5459],
       [  102,  1008],
       [  138,  8002],
       [  160,  6491],
       [  162,   311],
       [  169,  4136],
       [  175,  2160],
       [  188,   469],
       [  203,  7904],
       [  220,  8057],
       [  257,  9020],
       [  259,  4201],
       [  289, 10436],
       [  310,  5757],
       [  311,   162],
       [  384,  1720],
       [  414,  7194],
       [  416,  5795],
       [  435,  3886],
       [  457, 10006],
       [  463,  4505],
       [  469,   188],
       [  481,  9422],
       [  547,  3691],
       [  557,  7659],
       [  564,  1270],
       [  570,  4142],
       [  654,  2704],
       [  706,  3498],
       [  707,  7302],
       [  747,  9124],
       [  753,  2352],
       [  756,  7057],
       [  758,  4934],
       [  758,  8924],
       [  8

In [50]:


s = collections.defaultdict(list)
    
for x_id, y_id in groups:
    
    if y_id in s.keys():
        s[x_id].append(y_id)
    else:
        s[y_id].append(x_id)
    

In [51]:
s

defaultdict(list,
            {7809: [12],
             5629: [22],
             4819: [28],
             5537: [29],
             5014: [30],
             6284: [31, 4178],
             7904: [31, 31, 203],
             8473: [34],
             5459: [64],
             1008: [102],
             8002: [138],
             6491: [160],
             311: [162],
             4136: [169],
             2160: [175],
             469: [188],
             203: [7904],
             8057: [220],
             9020: [257],
             4201: [259],
             10436: [289],
             5757: [310],
             162: [311],
             1720: [384],
             7194: [414],
             5795: [416],
             3886: [435],
             10006: [457],
             4505: [463],
             188: [469],
             9422: [481],
             3691: [547],
             7659: [557],
             1270: [564],
             4142: [570],
             2704: [654],
             3498: [706],
             730

In [10]:
gkf = model_selection.GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
gkf_iterator = gkf.split(X=data.image_id, y=None, groups=data.isup_grade)

train_idx, valid_idx = next(gkf_iterator)

(array([    2,     3,    15, ..., 10612, 10614, 10615]),
 array([    0,     1,     4, ..., 10610, 10611, 10613]))

In [25]:
a = np.array([1,2,1,2,3,4,0,4,3,1,2,3,3,3,0,5,4,6,5,5,6])

gkf = model_selection.GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
gkf_iterator = gkf.split(X=a, y=None, groups=a)


In [26]:
train_idx, valid_idx = next(gkf_iterator)

print(a[train_idx])
print(a[valid_idx])

[2 2 3 4 4 3 2 3 3 3 5 4 6 5 5 6]
[1 1 0 1 0]
